hops_se/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
    url(r'^$', 'hops_se.views.home', name='home'),
    # url(r'^hops_se/', include('hops_se.foo.urls')),

    #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    #static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='auth_login'),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    
    url(r'^beer/$', 'beer.views.index'),
    url(r'^beer/(?P<beer_id>\d+)/$', 'beer.views.beer'),
    url(r'^beer/brewery/(?P<brewery_id>\d+)/$', 'beer.views.brewery'),
    url(r'^beer/review/(?P<review_id>\d+)/$', 'beer.views.review'),
	url(r'^beer/recipe/$', 'beer.views.recipes'),
	url(r'^beer/recipe/(?P<recipe_id>\d+)/$', 'beer.views.recipe'),
	url(r'^beer/add_beer/$', 'beer.views.add_beer'),
	url(r'^beer/add_brewery/$', 'beer.views.add_brewery'),
	url(r'^beer/add_town/$', 'beer.views.add_town'),
	url(r'^beer/recipe/add_comment/(?P<recipe_id>\d+)/$', 'beer.views.recipe_add_comment'),

	#url(r'^facebook/', include('django_facebook.urls')),
	#url(r'^accounts/', include('django_facebook.auth_urls')),
	#url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='auth_login'),
	#url(r'^logout/$', auth_views.logout, name='auth_logout'),/
	url(r'^noctoz_common/', include('noctoz_common.urls')),
	url(r'^auth/', include('noctoz_oauth.urls')),
)

beer/models.py
# encoding: utf-8
from django.db import models
from noctoz_common.models import ContentStreamItem
#from django_facebook.models import FacebookProfileModel
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.forms import ModelForm
from decimal import *

class Region(models.Model):
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name

class Country(models.Model):
	name = models.CharField(max_length=50)
	region = models.ForeignKey(Region)
	
	def __unicode__(self):
		return self.name

class Town(models.Model):
	name = models.CharField(max_length=50)
	country = models.ForeignKey(Country)
	
	def __unicode__(self):
		return self.name

class TownForm(ModelForm):
	class Meta:
		model = Town

class Brewery(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True, null=True)
	town = models.ForeignKey(Town)
	location_url = models.CharField(max_length=300, blank=True)
	picture = models.CharField(max_length=100, blank=True)

	def __unicode__(self):
		return self.name

class BreweryForm(ModelForm):
	class Meta:
		model = Brewery
		exclude = ('description', 'location_url', 'picture')

class Type(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True, null=True)
	
	def __unicode__(self):
		return self.name

class Beer(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True, null=True)
	picture = models.CharField(max_length=100, blank=True)
	type = models.ForeignKey(Type)
	brewery = models.ForeignKey(Brewery)
	abv = models.DecimalField(max_digits=4, decimal_places=2, default=0)
	sb_id = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

class BeerForm(ModelForm):
	class Meta:
		model = Beer
		exclude = ('description', 'picture')

class Review(ContentStreamItem):
	beer = models.ForeignKey(Beer)
	text = models.TextField(blank=True, null=True)
	score = models.IntegerField(default=0)
	affordability_index = models.DecimalField(max_digits=4, decimal_places=2, default=0)
	official = models.BooleanField(default=False)

	def __unicode__(self):
		return "Review of: " + self.beer.name

class BeerIngredient(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True, null=True)
	country = models.ForeignKey(Country)

	class Meta:
		abstract = True

class HopsType(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True, null=True)
	alpha_contrib = models.DecimalField(max_digits=6, decimal_places=2, default=0)
	
	def __unicode__(self):
		return self.name

class Hops(BeerIngredient):
	alpha = models.DecimalField(max_digits=6, decimal_places=2, default=0)
	HOPS_TYPES = (
		(u'cones', u'Kottar'),
		(u'pellets', u'Pellets'),
	)
	hops_type = models.CharField(max_length=10, choices=HOPS_TYPES, default='cones')

	def __unicode__(self):
		return u'%s, %f.2%%' % (self.name, self.alpha)

class MaltType(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True, null=True)
	extract_potential = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

class Malt(BeerIngredient):
	ebc = models.DecimalField(max_digits=6, decimal_places=2, default=0)
	dbfg = models.DecimalField(max_digits=5, decimal_places=2, default=0)
	mc = models.DecimalField(max_digits=5, decimal_places=2, default=0)
	protein = models.DecimalField(max_digits=5, decimal_places=2, default=0)
	malt_type = models.ForeignKey(MaltType)

	def __unicode__(self):
		return self.name

class YeastType(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True, null=True)
	
	def __unicode__(self):
		return self.name

class Yeast(BeerIngredient):
	fermentation_temp_min = models.IntegerField(default=0)
	fermentation_temp_max = models.IntegerField(default=0)
	ideal_temp_min = models.IntegerField(default=0)
	ideal_temp_max = models.IntegerField(default=0)
	alcohol_tolerance = models.IntegerField(default=0)
	YEAST_TYPES = (
		(u'dry', u'Torr'),
		(u'liquid', u'Flytande'),
	)
	yeast_type = models.CharField(max_length=10, choices=YEAST_TYPES, default='dry')
	attenuation = models.DecimalField(max_digits=3, decimal_places=1, default=0)
	cell_concentration = models.DecimalField(u"miljarder jästceller/g", max_digits=5, decimal_places=3, default=0)
	FLOCCULATION_TYPES = (
		(u'low', u'Låg'),
		(u'medium', u'Medium'),
		(u'high', u'Hög'),
	)
	flocculation = models.CharField(max_length=10, choices=FLOCCULATION_TYPES, default='medium')
	
	def __unicode__(self):
		return self.name

class MiscIngredient(BeerIngredient):
	extract_potential = models.IntegerField(default=0)
	
	def __unicode__(self):
		return self.name

class BeerRecipe(models.Model):
	beer = models.ForeignKey(Beer)
	start_water_volume = models.DecimalField(u"start vattenvolym", max_digits=4, decimal_places=2, default=0)
	final_volume = models.DecimalField(u"slutvolym", max_digits=4, decimal_places=2, default=0)
	mash_in_temp = models.IntegerField(u"inmäskningstemperatur", default=0)
	mashing_temp = models.IntegerField(u"mäskningstemperatur", default=0)
	mashing_time = models.IntegerField(u"mäskningstid", default=0)
	mash_out_temp = models.IntegerField(u"utmäskningstermperatur", default=0)
	mash_out_time = models.IntegerField(u"utmäskningstid", default=0)
	conversion_efficiency = models.IntegerField(u"konverteringseffektivitet", default=100)
	lauter_efficiency = models.IntegerField(u"lakningseffektivitet", default=100)
	pre_lauter_sg = models.DecimalField(u"SG innan lakning", max_digits=4, decimal_places=3, default=0)
	pre_boil_sg = models.DecimalField(u"SG innan kok", max_digits=4, decimal_places=3, default=0)
	og = models.DecimalField(u"OG", max_digits=4, decimal_places=3, default=0)
	fg = models.DecimalField(u"FG", max_digits=4, decimal_places=3, default=0)
	secret = models.BooleanField(default=False)
	creator = models.ForeignKey(User)
	group = models.ForeignKey(Group, null=True, blank=True)
	
	class Meta:
		permissions = (
			("view_recipe", "Can view recipe"),
			("view_secret_recipe", "Can view secret recipe"),
		)

	def __unicode__(self):
		return u'Recipe: %s, %d l' % (self.beer.name, self.final_volume)

class BeerRecipeForm(ModelForm):
	class Meta:
		model = BeerRecipe
		exclude = ('beer', 'secret', 'creator', 'group')

class NewBeerRecipeForm(ModelForm):
	class Meta:
		model = BeerRecipe
		fields = ('beer', 'secret', 'creator', 'group')

class HopsRecipeEntry(models.Model):
	recipe = models.ForeignKey(BeerRecipe)
	hops = models.ForeignKey(Hops)
	amount = models.IntegerField(default=0)
	add_time = models.IntegerField(default=0)

	def __unicode__(self):
		return u'%s: %s %d g, %d min' % (self.recipe.beer.name, self.hops.name, self.amount, self.add_time)

	def render(self):
		return u'%s %d g, %d min' % (self.hops.name, self.amount, self.add_time)

class MaltRecipeEntry(models.Model):
	recipe = models.ForeignKey(BeerRecipe)
	malt = models.ForeignKey(Malt)
	amount = models.DecimalField(max_digits=4, decimal_places=1, default=0)
	
	def __unicode__(self):
		return u'%s: %s %f g' % (self.recipe.beer.name, self.malt.name, self.amount)

	def render(self):
		return u'%s %d g, %d min' % (self.malt.name, self.amount, self.add_time)

class MiscIngredientEntry(models.Model):
	recipe = models.ForeignKey(BeerRecipe)
	ingredient = models.ForeignKey(MiscIngredient)
	amount = models.IntegerField(default=0)
	add_time = models.IntegerField(default=0)

	def __unicode__(self):
		return u'%s: %s %d g, %d min' % (self.recipe.beer.name, self.ingredient.name, self.amount, self.add_time)

class PrimaryFermentation(models.Model):
	recipe = models.ForeignKey(BeerRecipe)
	temp = models.IntegerField(default=0)
	time = models.DecimalField(max_digits=4, decimal_places=1, default=0)
	yeast = models.ForeignKey(Yeast, null=True, blank=True)
	yeast_amount = models.DecimalField(max_digits=4, decimal_places=1, default=0)
	TARGET_PITCH_TYPE = (
		(Decimal(0.35), u'Tillverkare'),
		(Decimal(0.5), u'Tillverkare 1.060+'),
		(Decimal(0.75), u'Ale'),
		(Decimal(1.0), u'Ale 1.060+'),
		(Decimal(1.5), u'Lager'),
		(Decimal(2.0), u'Lager 1.060+'),
	)
	target_pitch_rate = models.DecimalField(max_digits=4, decimal_places=2, default=0.75, choices=TARGET_PITCH_TYPE)

	def __unicode__(self):
		return u'%s: %d dagar' % (self.recipe.beer.name, self.time)

class SecondaryFermentation(models.Model):
	recipe = models.ForeignKey(BeerRecipe)
	temp = models.IntegerField(default=0)
	time = models.DecimalField(max_digits=4, decimal_places=1, default=0)

	def __unicode__(self):
		return u'%s: %d dagar' % (self.recipe.beer.name, self.time)

class DryHoppingRecipeEntry(models.Model):
	fermentation_stage = models.ForeignKey(SecondaryFermentation)
	hops = models.ForeignKey(Hops)
	amount = models.IntegerField(default=0)

	def __unicode__(self):
		return u'%s: %s %d g, %d min' % (self.fermentation_stage.recipe.beer.name, self.hops.name, self.amount)

class ExtraFlavourRecipeEntry(models.Model):
	fermentation_stage = models.ForeignKey(SecondaryFermentation)
	ingredient = models.ForeignKey(MiscIngredient)
	amount = models.IntegerField(default=0)
	
	def __unicode__(self):
		return u'%s: %s %d g, %d min' % (self.fermentation_stage.recipe.beer.name, self.ingredient.name, self.amount)

class PrimingEntry(models.Model):
	recipe = models.ForeignKey(BeerRecipe)
	SUGAR_TYPES = (
		(Decimal(0.35), u'Corn Sugar'),
		(Decimal(0.5), u'Anhydrous Glucose'),
		(Decimal(0.75), u'Bordssocker'),
		(Decimal(1.0), u'Torkat maltextrakt'),
	)
	sugar_type = models.DecimalField(max_digits=4, decimal_places=2, default=0.75, choices=SUGAR_TYPES)
	sugar_amount = models.DecimalField(max_digits=6, decimal_places=2, default=0.0)
	carbon_dioxide_concentration = models.DecimalField(max_digits=4, decimal_places=2, default=0.0)
	
	def __unicode__(self):
		return u'%s: Kolsyresättning' % (self.recipe.beer.name)

hops_se/views.py
from django.http import HttpResponse
from django.template import Context, loader, RequestContext
from django.contrib.contenttypes.models import ContentType
from beer.models import Review
from noctoz_common.models import NewsItem, Comment
from itertools import chain
from datetime import datetime
import operator
import json
import urllib2

def home(request):
	qs1 = Review.objects.all()
	qs2 = NewsItem.objects.all()
	#test1 = list(chain(qs1, qs2))
	test1 = sorted(chain(qs1, qs2), key = operator.attrgetter('pub_date'), reverse=True)
	#test1 = ContentContainer.objects.all()
	#test1 = ContentContainer.objects.select_related('review', 'newsitem')
	#output = ', '.join([type(p).__name__ for p in test1])
	latest_content = []
	float_right = False
	for content in test1:
		header = ""
		urlstr = ""
		comment_count = 0
		float_class = ""
		newline = False
		if isinstance(content, NewsItem):
			header = "Nyhet: " + content.header
			urlstr = "/noctoz_common/news/" + str(content.id)
		else:
			header = "Recension: " + content.beer.name
			urlstr = "/beer/review/" + str(content.id)
		
		content_type = ContentType.objects.get_for_model(content)
		comments = Comment.objects.filter(content_type__pk=content_type.id, object_id=content.id)
		comment_count = comments.count
			
		if float_right:
			float_class = "float-right"
			float_right = False
			newline = True
		else:
			float_class = "float-left"
			float_right = True
	
		latest_content.append({
			'urlstr': urlstr, 
			'header': header,
			'text': content.text, 
			'author': content.author, 
			'pub_date': content.pub_date,
			'comment_count': comment_count,
			'float_class': float_class,
			'newline': newline,
		})

	facebook_page_data = []

	#if request.user.is_authenticated():
		#if isinstance(request.user, HopsProfile):
		#facebook_profile = request.user.get_profile()
		#page_url = "https://graph.facebook.com/433896706654215/feed?access_token=" # + facebook_profile.access_token
		#facebook_page = json.load(urllib2.urlopen(page_url))
		
		#page_data = facebook_page["data"]
		#for page_entry in page_data:
		#	pub_date = datetime.strptime(page_entry["created_time"], "%Y-%m-%dT%H:%M:%S+0000")
		#	if page_entry["type"] == "link":
		#		facebook_page_data.append({
		#			'pub_date': pub_date,
		#			'message': page_entry["message"],
		#		})
		#	if len(facebook_page_data) == 5:
		#		break

		#facebook_page = json.load(urllib2.urlopen("http://graph.facebook.com/noctoz"))
		#facebook_page = page_url
            
	#t = loader.get_template('first_page.html')
	t = loader.get_template('first_page.html')
	c = RequestContext(request, {
		'latest_content': latest_content,
        'facebook_page': facebook_page_data,
	})
	return HttpResponse(t.render(c))

hops_se/templates/beer/beer.html
{% extends "base.html" %}

{% block content %}
<div class="beer-img"><img src="{{ beer.picture }}" height="150" width="150"></div>
<h2 class="content-header">{{ beer.name }}</h2>
<p class="content-post-date"><a href="/beer/brewery/{{ beer.id }}">{{ beer.brewery.name }}</a></p>
<p class="content-post-date">{{ beer.type }}, {{ beer.abv }}% </p>
<p class="content-post-date"><a href="http://systembolaget.se/{{ beer.sb_id }}" target="_blank">Systembolagets sida</a></p>
<div class="content-box-fix"></div>
<p>{{ beer.description|linebreaksbr }}</p>
<div class="content-box-fix"></div>
{% endblock %}

hops_se/templates/beer/brewery.html
{% extends "base.html" %}

{% block content %}
Namn: {{ brewery.name }}<br>
Stad: {{ brewery.town }}</br>
Land: {{ brewery.town.country }}<br>
Beskrivning:<br>
{{ brewery.description|linebreaksbr }}
{% endblock %}

hops_se/templates/beer/index.html
{% extends "base.html" %}

{% block content %}
{% if beer_list %}
	<ul>
	{% for beer in beer_list %}
		<li><a href="/beer/{{ beer.id }}/">{{ beer.name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No beers in database.</p>
{% endif %}
{% endblock %}

hops_se/templates/beer/recipe.html
{% extends "base.html" %}

{% block content %}
<div style="overflow:auto;">
<div class="beer-img"><img src="{{ recipe.beer.picture }}" height="150" width="150"></div>
<div class="content-post" style="float:left;">
	<h2 class="content-header">Recept: {{ recipe.beer.name }}</h2>
	<p class="content-post-data" contentEditable="true">Lite text om ölet</p>
</div>
</div>
<div class="content-box-newline"></div>
<div>
<hr/>
<h4>Vatten:</h4>
<p class="content-post-date">Start vattenvolym: <label id="startWaterVolume" contentEditable="true">{{ recipe.start_water_volume|floatformat:2 }}</label> liter </p>
<p class="content-post-date">Maxvolym: {{ max_volume|floatformat:2 }} liter</p>
<p class="content-post-date">Kokvolym: {{ boil_volume|floatformat:2 }} liter</p>
<p class="content-post-date">Beräknad slutvolym: {{ final_volume_estimate|floatformat:2 }} liter</p>
<p class="content-post-date">Slutvolym: {{ recipe.final_volume|floatformat:2 }} liter</p>
<hr/>
<h4>Mäskning:</h4>
<p class="content-post-date">Inmäskning: {{ recipe.mash_in_temp }} &deg;C</p>
<p class="content-post-date">Mäskning: {{ recipe.mashing_temp }} &deg;C, {{ recipe.mashing_time }} min</p>
<p class="content-post-date">Utmäskning: {{ recipe.mash_out_temp }} &deg;C, {{ recipe.mash_out_time }} min</p>
<p class="content-post-date">{{ form.conversion_efficiency.label }}: {{ recipe.conversion_efficiency }}%</p>
{% for entry in malt_entries %}
<p class="content-post-date">{{ entry.malt_data.amount }} kg {{ entry.malt_data.malt.name }}. {{ entry.malt_data.malt.ebc }} EBC. {{ entry.extract_potential }}% EP</p>
{% endfor %}
<p class="content-post-date">Vatten/Malt ratio: {{ water_malt_ratio|floatformat:3 }} liter/kg</p>
<p class="content-post-date">Viktad extraktionspotential: {{ extract_potential|floatformat:3 }}%</p>
<p class="content-post-date">EBC: {{ ebc|floatformat:2 }} </p>
<hr/>
<h4>Estimat innan mätningar:</h4>
<p class="content-post-date">SG innan kok (max): {{ potential_sg|floatformat:3 }}</p>
<p class="content-post-date">SG innan kok: {{ pre_boil_sg_adjusted|floatformat:3 }}</p>
<p class="content-post-date">OG (max): {{ og_potential|floatformat:3 }} </p>
<p class="content-post-date">OG: {{ og_adjusted|floatformat:3 }} </p>
<p class="content-post-date">FG: {{ fg_estimated2|floatformat:3 }} </p>
<p class="content-post-date">ABV: {{ abv_estimated2|floatformat:2 }} </p>
<hr/>
<h4>Uppmätt SG och beräkningar:</h4>
{% if recipe.pre_boil_sg > 0 %}
<p class="content-post-date">SG innan kok: {{ recipe.pre_boil_sg|floatformat:3 }}</p>
{% else %}
<p class="content-post-date">SG innan kok (från OG): {{ sg_from_og|floatformat:3 }}</p>
{% endif %}
<p class="content-post-date">Beräknad konverteringseffektivitet: {{ computed_brewhouse_eff|floatformat:2 }}%</p>
<hr/>
<h4>Kokning:</h4>
{% for entry in hops_entries %}
{% if entry.is_hops %}
<p class="content-post-date">{{ entry.recipe_entry.amount }} g {{ entry.recipe_entry.hops.name }} ({{ entry.recipe_entry.hops.alpha }}%). {{ entry.recipe_entry.add_time }} min. {{ entry.ibu|floatformat:2 }} IBU</p>
{% else %}
<p class="content-post-date">{{ entry.recipe_entry.amount }} g {{ entry.recipe_entry.ingredient.name }}. {{ entry.recipe_entry.add_time }} min</p>
{% endif %}
{% endfor %}
<hr/>
<h4>Uppmätt OG och beräkningar:</h4>
{% if recipe.og > 0 %}
<p class="content-post-date">OG: {{ recipe.og|floatformat:3 }} </p>
{% else %}
<p class="content-post-date">OG (från SG): {{ og_from_sg|floatformat:3 }} </p>
{% endif %}
<p class="content-post-date">Beräknad brygghuseffektivitet: {{ computed_brewhouse_eff|floatformat:2 }}% </p>
<p class="content-post-date">IBU Tinseth: {{ ibu_tinseth|floatformat:2 }} </p>
<p class="content-post-date">IBU Rager: {{ ibu_rager|floatformat:2 }} </p>
<p class="content-post-date">FG: {{ fg_estimated|floatformat:3 }} </p>
<p class="content-post-date">ABV: {{ abv_estimated|floatformat:2 }} </p>
<hr/>
<h4>Primärjäsning:</h4>
{% for stage in fermentation_stages %}
<p class="content-post-date">Jäst: {{ stage.yeast_amount }}g {{ stage.yeast.name }}</p>
<p class="content-post-date">Antal jästceller: {{ stage.yeast.cell_concentration }} miljarder/g</p>
<p class="content-post-date">Temperatur: {{ stage.temp }} &deg;C</p>
<p class="content-post-date">Jästid: {{ stage.time }} dagar</p>
<p class="content-post-date">Utjäsningsgrad: {{ stage.yeast.attenuation }}%</p>
<p class="content-post-date">Vald pitchgrad: {{ stage.target_pitch_rate }}</p>
{% endfor %}
<p class="content-post-date">Jästceller behov: {{ yeast_cells_needed|floatformat:2 }} miljarder</p>
<p class="content-post-date">Torrjäst behov: {{ dry_yeast_needed|floatformat:2 }} gram</p>
<p class="content-post-date">Beräknad pitchgrad: {{ computed_pitch_rate|floatformat:2 }}</p>
<hr/>
<h4>Uppmätt FG och beräkningar:</h4>
<p class="content-post-date">FG: {{ recipe.fg|floatformat:3 }} </p>
<p class="content-post-date">ABV Approx: {{ abv_approx|floatformat:2 }} </p>
<p class="content-post-date">ABV Exact: {{ abv|floatformat:2 }} </p>
<p class="content-post-date">Beräknad jästeffektivitet: {{ apparent_attenuation|floatformat:2 }}%</p>
<hr/>
<h4>Kolsyresättning:</h4>
{% for entry in priming_entries %}
<p class="content-post-date">Sockertyp: Bordssocker</p>
<p class="content-post-date">Kolsyrekoncentration: {{ entry.carbon_dioxide_concentration }}</p>
<p class="content-post-date">Mängd: {{ priming_sugar }} g</p>
{% endfor %}
<hr/>
<form method="post" action="">
	{% csrf_token %}
	{{form}}
<input type="submit">
</form>
<hr/>
<h4><a name="comments">Kommentarer:</a></h4>
{% for comment in comments %}
<p class="content-post-date"><b>{{ comment.author }}</b> {{ comment.pub_date|date:"Y-m-d H:i" }}</p>
<p class="content-post-date">{{ comment.text|linebreaksbr }}</p>
<hr/>
{% endfor %}
{% if user.is_authenticated %}
<h4>Skriv ny kommentar:</h4>
<form method="post" action="/beer/recipe/add_comment/{{ recipe.id }}/">
	{% csrf_token %}
	{{ comment_form.text }}<br/>
	<input type="submit">
</form>
{% endif %}

</div>
<script>
	$("#startWaterVolume").keypress(function(e) {
									return e.which != 13;
									});
	$("#startWaterVolume").bind("input", function() {
								
								$(this).css("font-weight","bold");
								$.post('',
									{
									   {{form.start_water_volume.name}}:$("#startWaterVolume").html(),
									   csrfmiddlewaretoken:'{{csrf_token}}'
									}, function(data) {
											alert(data);
									   }
									   );
								});
								
</script>
{% endblock %}

hops_se/templates/beer/recipes.html
{% extends "base.html" %}

{% block content %}
<h2 class="content-header">Alla Recept</h2>
{% for recipe in recipes %}
<p class="content-post-date"><a href="/beer/recipe/{{ recipe.id }}">{{ recipe.beer.name }}</a></p>
{% endfor %}
{% if perms.beer.add_beerrecipe %}
<hr/>
<h4>Lägg till nytt recept:</h4>
<form method="post" action="">
	{% csrf_token %}
	<input type="hidden" id="id_creator" name="creator" value="{{ user.id }}">
	{{ recipe_form.beer.label_tag }}:{{ recipe_form.beer }}
	{{ recipe_form.secret.label_tag }}:{{ recipe_form.secret }}
	{{ recipe_form.group.label_tag }}:{{ recipe_form.group }}
	<input type="submit">
</form>
<hr/>
{% if perms.beer.add_beer %}
<h4>Lägg till öl:</h4>
<form method="post" action="/beer/add_beer/">
	<input type="hidden" name="next" value="/beer/recipe/">
	{% csrf_token %}
	{{ beer_form }}
	<input type="submit">
</form>
{% if perms.beer.add_brewery %}
<hr/>
<h4>Lägg till bryggeri:</h4>
<form method="post" action="/beer/add_brewery/">
	<input type="hidden" name="next" value="/beer/recipe/">
		{% csrf_token %}
		{{ brewery_form }}
		<input type="submit">
</form>
{% if perms.beer.add_town %}
<hr/>
<h4>Lägg till stad:</h4>
<form method="post" action="/beer/add_town/">
	<input type="hidden" name="next" value="/beer/recipe/">
		{% csrf_token %}
		{{ town_form }}
		<input type="submit">
</form>
{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endblock %}

hops_se/templates/beer/review.html
{% extends "base.html" %}

{% block content %}
<div class="review-rating">{{ review.score }}</div>
<h2 class="content-header">Recension av: <a href="/beer/{{ review.beer.id }}">{{ review.beer.name }}</a></h2>
<p class="content-post-date">{{ review.pub_date|date:"d F Y, H:i" }}</p>
<div class="content-box-fix"></div>
<p>{{ review.text|linebreaksbr }}</p>
<div class="content-box-fix"></div>
{% endblock %}